set(CPACK_GENERATOR "STGZ")
set(CPACK_SOURCE_GENERATOR "TBZ2;TGZ;ZIP")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "A simple application to test QRegExps")
set(CPACK_PACKAGE_VENDOR "http://qregexp-editor.sf.com")
set(CPACK_PACKAGE_DESCRIPTION_FILE "${CMAKE_CURRENT_SOURCE_DIR}/COPYING")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/COPYING")
set(CPACK_RESOURCE_FILE_README "${CMAKE_SOURCE_DIR}/README")
set(CPACK_PACKAGE_VERSION "${QREGEXP-EDITOR_VERSION}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "${PROGRAM_NAME} ${QREGEXP-EDITOR_VERSION}")

set(CPACK_PACKAGE_NAME ${PROGRAM_NAME})
set(CPACK_PACKAGE_FILE_NAME
   "${PROGRAM_NAME}-${QREGEXP-EDITOR_VERSION}-${CMAKE_SYSTEM_NAME}-${CMAKE_SYSTEM_PROCESSOR}")
set(CPACK_PACKAGE_CONTACT "luis.artur.pereira@gmail.com")

if(UNIX)
   set(CPACK_STRIP_FILES "bin/qregexp-editor")
   set(CPACK_SOURCE_STRIP_FILES "")
   set(CPACK_PACKAGE_EXECUTABLES "qregexp-editor" "QRegExp-Editor")
endif(UNIX)

set(CPACK_SOURCE_PACKAGE_FILE_NAME "${PROGRAM_NAME}-${QREGEXP-EDITOR_VERSION}")
set(CPACK_SOURCE_IGNORE_FILES
  "/\\\\..*$;~$;/build/;~$;${CPACK_SOURCE_IGNORE_FILES}")

include(CPack)
